package com.skend.news.types;

public enum SectionType {
    GENERAL,
    WORLD,

//  UNITED STATES (USA)
    US,
    US_ECONOMY,
    US_COMPANIES,
    US_POLITICS,

//  COMPANIES
    COMPANIES,
    ENERGY_COMPANIES,
    MINING_COMPANIES,
    OIL_AND_GAS_COMPANIES,
    UTILITY_COMPANIES,
    INSURANCE_COMPANIES,
    TECHNOLOGY,
    TELECOMS,
    TRANSPORT_COMPANIES,
    AIRLINES,
    SHIPPING,
    RAIL,

//  MONEY
    FINANCIALS,
    BANKS,
    PROPERTY,
    FINANCIAL_SERVICES,
    MARKETS,
    ALPHAVILLE,
    CAPITAL_MARKETS,
    COMMODITIES,
    OIL,
    GOLD,
    COPPER,
    CURRENCIES,
    EQUITIES,
    US_EQUITIES,
    UK_EQUITIES,
    EUROPEAN_EQUITIES,
    APAC_EQUITIES,
    FUND_MANAGEMENT,
    FUND_REGULATION,
    PENSION_FUNDS,
    TRADING,
    CLEARING_AND_SETTLEMENT,
    HIGH_FREQUENCY_TRADING,
    TRADING_REGULATION,
    OTC_MARKETS,
    DERIVATIVES_TRADING,

//  HEALTH
    HEALTH,
    HEALTHCARE,
    PHARMACEUTICALS,

//  INDUSTRIES
    INDUSTRY,
    AEROSPACE_INDUSTRY,
    DEFENCE_INDUSTRY,
    AUTOMOBILES_INDUSTRY,
    BASIC_RESOURCES_INDUSTRY,
    CHEMICALS_INDUSTRY,
    CONSTRUCTION_INDUSTRY,
    INDUSTRIAL_GOODS_INDUSTRY,
    SUPPORT_SERVICES_INDUSTRY,

//  SERVICES
    PROFESSIONAL_SERVICES,
    ACCOUNTING_AND_CONSULTING_SERVICES,
    LEGAL_SERVICES,
    RECRUITMENT_SERVICES,

//  CONSUMER
    RETAIL_CONSUMER,
    CONSUMER_RETAIL,
    CONSUMER_FOOD_AND_BEVERAGE,
    CONSUMER_LUXURY_GOODS,
    CONSUMER_PERSONAL_AND_HOUSEHOLD_GOODS,
    CONSUMER_TOBACCO,
    CONSUMER_TRAVEL_AND_LEISURE,

    MEDIA,

    CLIMATE,

    BIG_READ,

}
